name: task_queues_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.3
  shared_preferences: ^2.0.6
  http: ^0.13.3
  rxdart: ^0.27.1
  json_annotation: ^4.0.1
  connectivity: ^3.0.6
  flutter_secure_storage: ^4.2.0
  carousel_slider: ^3.0.0
  flutter_screenutil: ^4.0.3+1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  meta: ^1.3.0
  equatable: ^2.0.3
  responsive_framework: ^0.1.2
  font_awesome_flutter: ^9.1.0
#  emoji_picker: ^0.1.0
  flutter_keyboard_visibility: ^5.0.3
  syncfusion_flutter_charts: ^19.2.56
  expandable: ^5.0.1
  drag_and_drop_lists: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  linter: ^1.6.1
  json_serializable: ^4.1.3
  build_runner:
  pedantic: null
#  flutter_launcher_icons: ^0.8.1
#  flutter_native_splash: ^1.2.3   #^0.1.9
#  flutter_rename_app: 1.0.0
  logger:
  effective_dart: ^1.3.0


# For information on the generic Dart part of this file, see the
# following ui: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: s # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en

#flutter_native_splash:
 # image: assets/images/logo2.png
 # color: "FFFFFF"
#  android_disable_fullscreen: true
# android: true
 # ios: true

flutter_icons:
  image_path: 'assets/images/app/app_icon.png'
  android: true
  ios: true

flutter_rename_app:
  application_name: Task Queues App
  dart_package_name: task_queues_app
  application_id: com.android.task_queues_app
  bundle_id: com.ios.task_queues_app
  android_package_name: com.AMI.task_queues_app

#flutter pub run flutter_rename_app
include: package:pedantic/analysis_options.yaml
analyzer:
  exclude:
    - "lib/presentation/localization/**"
  errors:
    missing_required_param: error
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
